Global:
  Source: "config(local)"
  ChangeMe: "v3"

Log:
  level: "info"
  development: false
  encoding: "console" # console or json
  encoderConfig:
    #  # https://godoc.org/go.uber.org/zap/zapcore#EncoderConfig
    timeKey: "ts"
    nameKey: "mylogger"
    messageKey: "msg"
    levelKey: "level"
    #  levelEncoder: "lowercase"
    callerKey: "caller"
  #  StacktraceKey: "stacktrace"
  outputPaths:
    - "stdout"
    - "./trash.log"
  #errorOutputPaths:
  #  - "stderr"
  #initialFields:
  #  foo: "bar"

Server:
  Address: "127.0.0.1"
  Port: 8080

Client:
  Echo: true
  Foo: "bar"
  Servers:
    - "127.0.0.1"
    - "192.168.1.1"
