/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window (void)
{
  GtkWidget *window;
  GtkWidget *table;
  GtkWidget *info;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window), _("Message dialogs"));
  gtk_window_set_default_size (GTK_WINDOW (window), 220, 150);

  table = gtk_table_new (2, 2, TRUE);
  gtk_widget_show (table);
  gtk_container_add (GTK_CONTAINER (window), table);
  gtk_container_set_border_width (GTK_CONTAINER (table), 15);
  gtk_table_set_row_spacings (GTK_TABLE (table), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table), 2);

  info = gtk_button_new_from_stock ("gtk-about");
  gtk_widget_show (info);
  gtk_table_attach (GTK_TABLE (table), info, 0, 1, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 3, 3);
  gtk_widget_add_accelerator (info, "activate", accel_group,
                              GDK_a, (GdkModifierType) GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);

  g_signal_connect ((gpointer) window, "destroy",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect_swapped ((gpointer) info, "clicked",
                            G_CALLBACK (show_info),
                            GTK_OBJECT (aboutdialog));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window, window, "window");
  GLADE_HOOKUP_OBJECT (window, table, "table");
  GLADE_HOOKUP_OBJECT (window, info, "info");

  gtk_window_add_accel_group (GTK_WINDOW (window), accel_group);

  return window;
}

GtkWidget*
create_aboutdialog (void)
{
  GtkWidget *aboutdialog;
  /* TRANSLATORS: Replace this string with your names, one name per line. */
  gchar *translators = _("translator-credits");
  GtkWidget *dialog_vbox;

  aboutdialog = gtk_about_dialog_new ();
  gtk_container_set_border_width (GTK_CONTAINER (aboutdialog), 5);
  gtk_about_dialog_set_version (GTK_ABOUT_DIALOG (aboutdialog), VERSION);
  gtk_about_dialog_set_name (GTK_ABOUT_DIALOG (aboutdialog), _("Application Name"));
  gtk_about_dialog_set_comments (GTK_ABOUT_DIALOG (aboutdialog), _("O' Rly?"));
  gtk_about_dialog_set_translator_credits (GTK_ABOUT_DIALOG (aboutdialog), translators);

  dialog_vbox = gtk_vbox_new (FALSE, 2);
  gtk_widget_show (dialog_vbox);
  gtk_container_add (GTK_CONTAINER (aboutdialog), dialog_vbox);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (aboutdialog, aboutdialog, "aboutdialog");
  GLADE_HOOKUP_OBJECT (aboutdialog, dialog_vbox, "dialog_vbox");

  return aboutdialog;
}

