#include <libwp.h>
#include "square.h"	/* generated by rpcgen */

int main (int argc, char *argv[])
{
	CLIENT *cl;
	square_in in;
	square_out *outp;

	if (argc != 3)
		wp_critical ("usage: %s <hosname> <integer-value>", argv[0]);
	
	cl = clnt_create (argv[1], SQUARE_PROG, SQUARE_VERS, "tcp");
	in.arg1 = atol (argv[2]);
	if ((outp = squareproc_1 (&in, cl)) == NULL)
		wp_critical ("%s", clnt_sperror (cl, argv[1]));

	printf ("result: %ld\n", outp->res1);
	return 0;
}
