bench:
	-fl-run-bench launcelot_test.py TestLauncelot.test_dialog
	fl-build-report --html bench.xml
test:
	fl-run-test launcelot_test.py TestLauncelot.test_dialog
clean:
	rm -rf *.xml* *.log test_dialog*
